# Generated by Django 3.0 on 2020-04-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('createion_date', models.DateField(auto_now=True)),
                ('description', models.TextField(max_length=75)),
            ],
        ),
    ]
