# Generated by Django 3.0 on 2020-04-22 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200423_0147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='createion_date',
            new_name='creation_date',
        ),
    ]
